name: Deploy React via SSH and Docker Compose

# Pemicu workflow -> dijalankan saat ada push ke branch main atau bisa dijalankan manual
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # perintah untuk pull, rebuild dan migrasi
      - name: Connect to server, pull code, and rebuild docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CI_CD_SERVER_2 }}
          username: ${{ secrets.CI_CD_USER }}
          key: ${{ secrets.CI_CD_PASSWORD }}
          script: |
            set -e

            cd /opt/production/smartfarming/FE_Smart_Farming

            git config --global --add safe.directory /opt/production/smartfarming/FE_Smart_Farming

            echo "Pulling latest code from origin main..."
            git pull origin main

            echo "Building new Docker image without cache..."
            sudo docker compose build --no-cache frontend_react

            echo "Recreating and starting container..."
            sudo docker compose up -d --force-recreate frontend_react

            echo "Deployment finished successfully!"
